Change firewall_apply behavior
dhozac/socrates_api pull request #14
Opened 2020-10-13 12:16 UTC by acalm

As title suggests, the function will not do any kind of formatting and just pass address groups, networks and rulesets on to Ansible

2020-10-13 15:57 UTC, dhozac requested changes
Looks good! I think this means we can probably drop some of the resolve code from the serializers as well, if you want to get an even higher score!

2020-10-13 15:57 UTC, dhozac commented on socrates_api/serializers.py
> +            firewall_apply.apply_async((asset))
This is missing a trailing comma to make it a tuple.

2020-10-13 15:57 UTC, dhozac commented on socrates_api/serializers.py
> +                    firewall_apply.apply_async((asset))
Same here.

2020-10-13 16:39 UTC, acalm commented
> Looks good! I think this means we can probably drop some of the resolve code from the serializers as well, if you want to get an even higher score!

Well, I do like higher scores!

2020-10-14 08:31 UTC, dhozac commented
This will need to update testdata/playbooks/firewall-apply.yml as well to look for the new variables.

2020-10-14 14:38 UTC, merged